### PR TITLE
Dashboard-Frontend

### PR DESCRIPTION
**Pull request by PavelCA04**
Elaborated a dashboard for the administrative area of the pet shop, in this dashboard you can find multiple modules, including Client Management, Appointment Management, Medical Files Management, and User Management. Also included the elaboration of the login and a register pet option.

### CODE REVIEW

**Comment by tonybarr1611** [comment]
Page is live and working at:
https://mypetcr.netlify.app/

**Review by sfabricito — APPROVED** [review]
I approved the implementation of the dashboard in the frontend.

**Comment by andco97** [comment]
Good explanation. Very thorough. Approved.

**Review by andco97 — APPROVED** [review]
Good explanation. Very thorough. Approved.

**Pull request merged**
